services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-puskesmas
    container_name: puskesmas-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - puskesmas-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: puskesmas-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - puskesmas-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: puskesmas-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: puskesmas_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: user_password
      MYSQL_USER: laravel_user
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - puskesmas-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Service
  redis:
    image: redis:alpine
    container_name: puskesmas-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - puskesmas-network

  # Queue Worker
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puskesmas-queue
    restart: unless-stopped
    command: sh -c "wait-for-it.sh db:3306 --timeout=60 --strict -- php artisan queue:work --verbose --tries=3 --timeout=90"
    volumes:
      - ./:/var/www/html
    networks:
      - puskesmas-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # Scheduler
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puskesmas-scheduler
    restart: unless-stopped
    command: sh -c "wait-for-it.sh db:3306 --timeout=60 --strict -- php artisan schedule:run"
    volumes:
      - ./:/var/www/html
    networks:
      - puskesmas-network
    depends_on:
      db:
        condition: service_healthy

# Docker Networks
networks:
  puskesmas-network:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local
